FROM python:3.12-slim

# Evita que Python escriba archivos .pyc y fuerza salida de stdout
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Instalar dependencias del sistema necesarias para PostgreSQL
RUN apt-get update \
    && apt-get install -y gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copiar el archivo de requerimientos e instalar dependencias
COPY requerimientos.txt /app/
RUN pip install --no-cache-dir -r requerimientos.txt

# Copiar el resto del código
COPY . /app/

# El comando se ejecutará desde el docker-compose.yml
